# Generated by Django 3.1.6 on 2021-12-26 14:17

from django.db import migrations, models
import django.db.models.deletion
import image_service.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название изображения')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=image_service.utils.create_path_image_data, verbose_name='Изображение')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина изображения')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота изображения')),
                ('parent_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_service.imagedata', verbose_name='Родительское изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
