version: '3.7'

services:
  backend:
    build:
      context: ./backend
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/app/:cached
      - static:/app/static/:delegated
    ports:
    - 8000:8000
    depends_on:
    - db


  db:
    image: postgres:12.3-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:6.0-alpine
    volumes:
      - redisdata:/data

volumes:
  static:
  redisdata:
  postgresdata:
